getnacelle/nacelle-react

examples/nextjs/components/CollectionGrid/CollectionGrid.js, examples/nextjs/components/CollectionGrid/index.js, examples/nextjs/components/ContentSections/ContentSections.js
Feature for [[NC-1620](https://nacelle.atlassian.net/browse/NC-1620)]
This adds the CollectionGrid component which is rendered through ContentSection as case "collectionGrid".
Screenshot of the bottom of the hero banner to the CollectionGrid of 'eyewear':
Currently in Prairie Wind Apparel, there is a collection content section (in contentful) on the homepage for eyewear that should display directly below the hero banner. This should be rendered.
=> Add CollectionGrid component

README.md, examples/gatsby/.eslintrc.js, examples/gatsby/package.json, examples/gatsby/src/pages/index.js, examples/nextjs/components/Header/Header.js, examples/nextjs/components/SearchBar/SearchResult.js, examples/nextjs/package.json, examples/withKlaviyo/package.json, examples/withRecharge/package.json, examples/withYotpo/package.json, lerna.json, package-lock.json, package.json, packages/component-library/package.json, packages/component-library/src/components/TextInput/TextInput.tsx, packages/gatsby-source-nacelle/.eslintrc.js, packages/gatsby-source-nacelle/gatsby-node.js, packages/gatsby-source-nacelle/package.json, packages/react-hooks/package.json, packages/react-klaviyo/package.json, packages/react-klaviyo/src/components/KlaviyoScripts/KlaviyoScripts.tsx, packages/react-recharge/package.json, packages/react-yotpo/package.json, packages/react-yotpo/src/components/YotpoScripts/YotpoScripts.tsx
- `lint-staged` was not being run across all projects before committing to the monorepo
- There was some confusion on the workflow when installing dependencies / setting up new examples & packages
- The new gatsby projects did not have linting setup
- Development dependencies were captured in each individual repo; storing them in the monorepo package.json ensures consistent versioning for things like Jest, Eslint, etc
Fixes [[NC-1676](https://nacelle.atlassian.net/browse/NC-1676)] 
- Moves husky git-hooks to the monorepo package.json
- Adds `precommit` hook to each of the repositories that will lint staged files
- Added new information to the monorepo README
- Added linting to Gatsby projects
- Moved dev dependencies into monorepo package.json to ensure consistent versioning
=> [all]: Update Handling of Dev Dependencies and Improve Monorepo Docs

examples/nextjs/services/nacelle.js
This PR addresses [DRMS-724](https://nacelle.atlassian.net/browse/DRMS-724):
> Fix Nacelle Preview env var evaluation in Next.js example
In the Next.js example project, when a `NACELLE_PREVIEW_MODE` environment variable was provided as `false`, preview mode was still enabled due to failure to account for the (`String`) type of the environment variable provided to the app by `dotenv`.
With this change, the Contentful preview connector is activated only when `NACELLE_PREVIEW_MODE=true` in `.env`.
In addition, if the user has `NACELLE_PREVIEW_MODE=true` but is missing the required variables to use preview mode, a console warning is provided to tell the user which environment variables are missing.
[`examples/nextjs`]
---
With the following `.env`:
``` …
```
=> Fix Preview Mode Logic Gate

package.json, packages/gatsby-source-nacelle/package.json, packages/gatsby-source-nacelle/src/utils/createRemoteImageFileNode.js
**Story:** [ENG-233](https://nacelle.atlassian.net/browse/ENG-233) 
> [gatsby-source-nacelle] don't include gatsby-source-filesystem by default
We want devs using `gatsby-source-nacelle` to be able to opt in to using Gatsby Image. Currently, devs installing `gatsby-source-nacelle` will unwittingly be opting in to using Gatsby Image unless they install via `@nacelle/gatsby-source-nacelle` with the [`--no-optional`](https://docs.npmjs.com/cli/v6/commands/npm-install) flag.
This PR removes `gatsby-source-filesystem` from the [`optionalDependencies`](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#optionaldependencies) and adds it to the [`peerDependencies`](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#peerdependencies). This way, `gatsby-source-filesystem` is not …
=> Use Correct Dependency Type for Gatsby-Source-Filesystem

packages/react-recharge/scripts/expose-metafields.js
Fix typo in the expose-metafields script (#27)
- It only adds an `s` to the `validateMetafields` method.
- Without that extra `s` the `npx expose-metafield` will crash because the code is looking for a namespace on the metafields called `subscriptions`.
=> Fix typo in the expose-metafields script

examples/nextjs/.env.example, examples/nextjs/README.md, examples/nextjs/package.json, examples/nextjs/pages/api/exit-preview.js, examples/nextjs/pages/api/preview.js, examples/nextjs/pages/collections/[handle].js, examples/nextjs/pages/index.js, examples/nextjs/pages/pages/[handle].js, examples/nextjs/pages/products/[handle].js, examples/nextjs/pages/shop.js, examples/nextjs/services/nacelle.js, package.json
Fixes [NS-539](https://nacelle.atlassian.net/browse/NS-539)
> Nacelle Shopify Connector throwing ECONNREFUSED 127.0.0.1:80 in NextJS
This PR enables Shopify previews via the [`@nacelle/shopify-connector`](https://www.npmjs.com/package/@nacelle/shopify-connector), and explains the use of new API routes in the README.
https://user-images.githubusercontent.com/5732000/109194151-26ba1c00-7767-11eb-870f-b987042ce2e1.mov
visit [`https://nacelle-nextjs-example-git-ns-539-nacelle.vercel.app/api/preview?path=/products/dania-glasses`](https://nacelle-nextjs-example-git-ns-539-nacelle.vercel.app/api/preview?path=/products/dania-glasses)
=> [nextjs] Configure API Routes for Previewing Products, Collections, and Content

packages/react-hooks/README.md, packages/react-hooks/src/hooks/use-cart/index.ts, packages/react-hooks/src/hooks/use-cart/use-cart.provider.tsx, packages/react-hooks/src/hooks/use-cart/use-cart.types.ts
Fixes [DMS-1465](https://nacelle.atlassian.net/browse/DMS-1465)
> Fix incorrect types for useCart
- [Assert](https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions) that the `return` value of `useCart` is a [Tuple](https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple): `[CartState, CartActions]` to prevent incorrect type inference of `(CartActions | CartState)[]`
- Use correct typing of React children as `JSX.Element | JSX.Element[]`
https://user-images.githubusercontent.com/5732000/112369722-e476f280-8cb2-11eb-950c-559e29b93e76.mov
No errors!
In `packages/react-hooks/README.md`:
- Fixes typo (`useCheckout` --> `useCart`)
- Explains role of `useLocalStorage` prop in `<CartProvider />`
- Enable cart persistence via Local Storage by default
- Spin up a …
=> [react-hooks] Fix Types

examples/gatsby/package.json, examples/nextjs/components/Cart/Cart.js, examples/nextjs/components/ItemQuantity/ItemQuantity.js, examples/nextjs/components/ProductCard/ProductCard.js, examples/nextjs/package.json, examples/withRecharge/package.json, lerna.json, packages/react-hooks/package.json, packages/react-hooks/src/hooks/use-cart/use-cart.provider.tsx, packages/react-hooks/src/hooks/use-cart/use-cart.reducer.ts, packages/react-hooks/src/hooks/use-cart/use-cart.types.ts
Fixes [DMS-1529](https://nacelle.atlassian.net/browse/DMS-1529)
> In certain cases, useCart hook's cartActions.addToCart doesn't respect a quantity other than 1
Which in turn unblocks [NS-629](https://nacelle.atlassian.net/browse/NS-629) and [NS-632](https://nacelle.atlassian.net/browse/NS-632)
When an item was added to cart, and then more than 1 more of that item were added to cart, the item's cart quantity would only increment by 1:
https://user-images.githubusercontent.com/5732000/113362118-98aff300-931b-11eb-9c93-9de2a5a5ba44.mov
In `packages/react-hooks/src/hooks/use-cart/use-cart.reducer.ts`, defer to the `payload.quantity` as the value to increment quantity by.
Allow the `toggleCart()` function in `cartActions` to accept an argument of `'open'` or `'closed'`, in order to allow …
=> [packges/react-hooks; examples/nextjs] Fix Add-to-Cart Quantity Bugs

packages/react-hooks/src/hooks/use-cart/use-cart.types.ts
**Story:** [DD-234](https://nacelle.atlassian.net/browse/DD-234)
> In @nacelle/react-hooks, an enum isn't exported
It turns out that [enums can't be exported directly](https://stackoverflow.com/a/62652759/6387812), and need a variable declaration in order to work as expected. An enum was [added](packages/react-hooks/src/hooks/use-cart/use-cart.types.ts) in #41.
- Checkout the `DD-234` branch
- Build / deploy a site that uses `@nacelle/react-hooks`' `useCart` hook
=> [packages/react-hooks] Fix useCart bug with un-exported enum

examples/gatsby/src/components/Cart/Cart.js, examples/nextjs/components/Cart/Cart.js, examples/withRecharge/pages/index.js, packages/react-hooks/src/common/types.ts, packages/react-hooks/src/hooks/use-checkout/use-checkout.test.ts, packages/react-hooks/src/hooks/use-checkout/use-checkout.ts
**Story:** [DD-290](https://nacelle.atlassian.net/browse/DD-290)
> In @nacelle/react-hooks useCheckout hook, add metafields, note, and source to checkout input params
- Instead of passing an array of `[credentials, lineItems, checkoutId]` to the `useCheckout` hook, pass a `params` object with `{ credentials, lineItems, checkoutId?, metafields?, note?, discountCodes?, source? }`
-  Previously, `metafields`, `note`, `discountCodes`, and `source` were not accepted by `useCheckout` and sent as `variables` for Hail Frequency's `checkoutProcess` mutation
- The number of params has grown to the point that they should be passed by name, in an object
- Changing the input parameters from an array to an object represents a breaking change
- Filters `CheckoutInput.cartItems[idx].metafields` …
=> [packages/react-hooks | v3.0.0] Accept All Supported CheckoutInput Params in useCheckout

examples/gatsby/gatsby-browser.js, examples/nextjs/pages/_app.js, packages/react-hooks/README.md, packages/react-hooks/src/hooks/use-cart/actions/addToCart.ts, packages/react-hooks/src/hooks/use-cart/actions/clearCart.ts, packages/react-hooks/src/hooks/use-cart/actions/decrementItem.ts, packages/react-hooks/src/hooks/use-cart/actions/incrementItem.ts, packages/react-hooks/src/hooks/use-cart/actions/removeFromCart.ts, packages/react-hooks/src/hooks/use-cart/actions/toggleCart.ts, packages/react-hooks/src/hooks/use-cart/actions/updateItem.ts, packages/react-hooks/src/hooks/use-cart/use-cart.provider.tsx, packages/react-hooks/src/hooks/use-cart/use-cart.reducer.test.ts, packages/react-hooks/src/hooks/use-cart/use-cart.reducer.ts, packages/react-hooks/src/hooks/use-cart/use-cart.types.ts, packages/react-hooks/src/hooks/use-cart/utils/index.ts
**Story:** [DD-428](https://nacelle.atlassian.net/browse/DD-428)
> As a merchant developer, I want to be able to customize @nacelle/react-hooks' use of the Storage API, so that I have more control of my customer's cart persistence
_Non-Breaking Change_
When persisting the cart in browser storage, the key `'cart'` was used, without any ability to control the key name. This can cause headaches when migrating from `@nacelle/react-hooks@3.x`, which formatted `CartItems`s differently.
This change allows merchant developers to upgrade from  `@nacelle/react-hooks@3.x` without creating any collisions between mis-matched carts in `localStorage`, for example, when customers who have an older cart saved in their `localStorage`.
https://user-images.githubusercontent.com/5732000/117478517-43c05780-af2d …
=> [packages/react-hooks] Added Flexibility for Cart Storage

examples/gatsby/src/components/Cart/Cart.js, examples/gatsby/src/components/ProductGallery/ProductGallery.js, examples/gatsby/src/providers/ProductSearch.js, examples/nextjs/components/Cart/Cart.js, examples/nextjs/components/ProductGallery/ProductGallery.js, examples/nextjs/providers/ProductSearch.js, package.json, packages/react-hooks/src/hooks/common/types.ts, packages/react-hooks/src/hooks/use-cart/use-cart.provider.tsx, packages/react-hooks/src/hooks/use-cart/use-cart.types.ts, packages/react-hooks/src/hooks/use-cart/utils/index.ts, packages/react-hooks/src/hooks/use-checkout/use-checkout.types.ts
**Story:** [DD-442](https://nacelle.atlassian.net/browse/DD-442)
> As a merchant developer, I want @nacelle/react-hooks to remain compatible with my customer's old cart persisted in local storage, so that I don't need to delete their persisted cart
For customers who have a cart containing `CartItem`s in the format used in `@nacelle/react-hooks` versions `1.x`, `2.x`, and `3.x` persisted in local storage, the old `CartItem`s are mapped to the new-style (`4.0.0` and above) `CartItem` format
From the monorepo root,
- `npm run bootstrap && cd packages/react-hooks && npm run build`
- navigate to either `examples/gatsby` or `examples/nextjs` and `npm run dev`
- with an example project running, open the developer tools and clear out any existing `cart` entry in local storage, then refresh
-  in …
=> [packages/react-hooks] Add Support for Legacy Cart Items in Browser Storage

packages/react-hooks/src/hooks/use-cart/actions/updateItem.ts, packages/react-hooks/src/hooks/use-cart/use-cart.reducer.test.ts
[DD-756](https://nacelle.atlassian.net/browse/DD-756)
> @nacelle/react-hooks `cartActions.updateItem(item)` updates every item in the cart with properties of the `item` param
#53 identified an issue with the `updateItem` action, in which `updateItem` would erroneously run on every item in the cart, instead of on the item of interest. This PR adds unit tests to check that this doesn't happen, and adds a small change to the `updateItem` action to fix the issue, without any API changes.
https://user-images.githubusercontent.com/5732000/122834168-17ce1b00-d2bc-11eb-84fa-51219059bdd2.mov
- CI for this PR should pass
- Unit tests should pass
- Pull the `DD-756-updateItem-bugfix` branch
- `npm run bootstrap` from monorepo root
- `cd packages/react-hooks && npm run test`
- Publish …
=> [packages/react-hooks] Fix Bug in `updateItem` Action

examples/nextjs/pages/[blogHandle]/[handle].js, examples/nextjs/pages/api/preview.js, examples/nextjs/utils/preview/getPathFromData.js, examples/nextjs/utils/preview/handleRedirect.js
[DD-772](https://nacelle.atlassian.net/browse/DD-772)
> Fix previewData bug in getPathFromData preview util function
This PR fixes a couple of oversights from #55:
-  the `examples/nextjs/utils/preview/getPathFromData.js` utility function was using the old `preview: true` instead of passing the `previewData` that the `nacelleClient` needs in order to fetch preview data
- article routes weren't handled correctly in `/api/preview`, and weren't passing `previewData` to the `nacelleClient` in the article page template
With this PR, `previewData` is used as a named export `examples/nextjs/utils/preview/getPathFromData.js`, which means that the merchant developer only needs to use Shopify / Contentful / Sanity-specific environment variables in one place. This makes it easier to configure …
=> [examples/nextjs] Use Consistent `previewData` in Next.js Preview Utils

packages/react-hooks/src/hooks/use-checkout/async-handlers/processCheckout.ts
[DD-819](https://nacelle.atlassian.net/browse/DD-819)
> For Shopify checkouts, apply discount code via checkout URL query param in @nacelle/react-hooks' processCheckout function
Until full `discountCodes` support for Shopify is added to Hail Frequency, this PR bridges the gap by adding a `discount=some-discount-code` query parameter for Shopify checkouts, using `discountCodes[0]`.
This PR has been end-to-end tested with the Next.js example project (see demonstration below), with and without `discountCodes`.
Check out the `DD-819-shopify-checkout-discount-code` branch.
From the monorepo root:
- `npm run bootstrap`
- `cd packages/react-hooks && npm run build && npm run test:ci`
- in an example project, add a valid discount code in the `discountCodes` that are accepted by the …
=> [packages/react-hooks|DD-819] Add discount query param for Shopify checkouts

examples/nextjs/pages/_app.js, packages/react-hooks/README.md, packages/react-hooks/package.json, packages/react-hooks/src/hooks/use-cart/actions/index.ts, packages/react-hooks/src/hooks/use-cart/actions/initCart.ts, packages/react-hooks/src/hooks/use-cart/use-cart.provider.tsx, packages/react-hooks/src/hooks/use-cart/use-cart.reducer.test.ts, packages/react-hooks/src/hooks/use-cart/use-cart.reducer.ts, packages/react-hooks/src/hooks/use-cart/use-cart.types.ts, packages/react-hooks/src/hooks/use-cart/utils/index.ts, packages/react-hooks/src/hooks/use-checkout/checkout-requests/getCheckout.ts, packages/react-hooks/src/hooks/use-checkout/checkout-requests/processCheckout.ts
**What This PR Does**
- Adds `indexdb` storage options for `useCart` hook per merchant request: https://nacelle.atlassian.net/browse/LD-441
- Updates `CartProvider` to dispatch initial `cartReducer` state inside of `useEffect`
- Adds test for initializing the cart
**How To Test**
- Checkout this branch locally and build `react-hooks`.
- Update the nextjs examples project to set the storage option to `idb` 
```
<CartProvider storage={'idb'}>
```
- Make cart updates, and then hard reload page.
**Notes**
- During initial testing the cart icon count seemed off.  But after further investigation it looks to calculate the total number of unique items in cart, not the total quantity of items in cart
- 2 of variant 123 = 1 item in cart
- 2 of variant 123, 1 of variant 234 = 2 items in cart
=> LD441 - index db option for useCart

packages/react-yotpo/README.md
**What This PR Does**
- updates `YotpoStarRatings` in README.md to use `pimSyncSourceId` instead of `shopifyProductId`
=> docs: productId prop

CONTRIBUTING.md, README.md
**Story:** [LS-1305](https://nacelle.atlassian.net/browse/LS-1305)
> Rewrite Nacelle React Readme to be explicit on how to interact with it as a merchant developer vs a repo contributor
Chore (docs, refactor, etc)
The README was giving merchant developers the impression that they should clone the entire `nacelle-react` monorepo in order to work with `examples/*` projects. This caused headaches when scaffolding a new project with `examples/gatsby` / `examples/nextjs`.
This PR:
1. Moves monorepo-specific / local development guidelines to `CONTRIBUTING.md`.
2. Gives explicit instructions in `README.md` for scaffolding new projects from `examples/*` projects, without the need to clone and bootstrap the `nacelle-react` monorepo.
Check out …
=> docs: encourage project scaffolding without cloning

examples/gatsby/gatsby-config.js, packages/gatsby-source-nacelle/README.md, packages/gatsby-source-nacelle/gatsby-node.js
**Story:** [LS-1414](https://nacelle.atlassian.net/browse/LS-1414) 
1. Adds a nacelleClient option to the gatsby plugin that allows users to pass in their own client.
2. Updates the gatsby example to use this option
1. Pull `LS-1414-allow-users-to-pass-in-client-sdk`
2. Test a build with `npm run build` in the root of the repo
3. Build the gatsby example by navigating to `examples/gatsby` and running `npm run build`
1. You may need to get the `.env` variables from Vercel
=> feat(gatsby): add option to pass Nacelle client to gatsby plugin

examples/gatsby/src/components/Cart/Cart.js, examples/nextjs/components/Cart/Cart.js, examples/nextjs/pages/_app.js, packages/react-hooks/src/hooks/use-checkout/use-checkout.provider.tsx, packages/react-hooks/src/hooks/use-checkout/use-checkout.types.ts
[LS-1458](https://nacelle.atlassian.net/browse/LS-1458)
> Race condition in processCheckout in nacelle-react/examples/{nextjs|gatsby}
Bug fix (will bump to `6.1.1`).
The `<Cart />` component's `processCheckout` handler was encountering a race condition (described in the ticket). We can avoid the race condition by leveraging the value of the resolved `checkoutActions.processCheckout` Promise, which contains the checkout `url` that the customer gets redirected to.
As of [`@nacelle/react-hooks@6.0.0`](https://nacelle.atlassian.net/wiki/spaces/PI/pages/1252819054/nacelle+react-hooks#Redirecting-customers-to-checkout), the `redirectUserToCheckout` prop does nothing. This PR adds a deprecaction warning in the console and advises the merchant developer to handle the customer's redirect to …
=> (fix): race condition in processCheckout
